test123/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import  settings
from django.conf.urls.static import static
from user import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
]
urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.routers import SimpleRouter
from rest_framework_jwt import views as jwt


router = SimpleRouter()

router.register('register', views.UserList, 'register')

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.registration, name='register'),
    url(r'^login/$', views.Login, name='Login'),
    url(r'^logout/$', views.Logout, name='Logout'),
    url(r'^api/token/refresh/$', jwt.refresh_jwt_token),
    url(r'^api/token/verify/$', jwt.verify_jwt_token),
    url(r'^api/token/$', jwt.obtain_jwt_token),
    url(r'^upkml/$', views.upkml, name='upkml'),
    #url(r'^test/$', views.test, name='upkml'),
    url(r'^check/(?P<plot_id>[0-9]+)/$', views.check_plot, name='check_plot'),
    url(r'^plot/$', views.PlotView.as_view(), name='plot'),
    url(r'^plot/detail/(?P<plot_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^plot/update_plot/(?P<plot_id>[0-9]+)/$', views.update_plot, name='update_plot'),
    url(r'^plot/(?P<plot_id>[0-9]+)/$', views.public, name='public'),
    url(r'^plot/([0-9]+)/detail/(?P<id>[0-9]+)/$', views.detail_public, name='public_detail'),
    url(r'^plot/([0-9]+)/update_public/(?P<id>[0-9]+)/$', views.update_public, name='update_public'),
    url(r'^check_public/(?P<id>[0-9]+)/$', views.check_public, name='check_public'),
    url(r'^add_kml_poi/$', views.add_kml_poi, name='add_kml_poi'),
    url(r'^create_poi/$', views.create_poi, name='create_poi'),
    url(r'^create_poi_form/$', views.create_poi_form, name='create_poi_form'),
    url(r'^create_floor_form/$', views.create_floor_form, name='create_floor_form'),
    url(r'^add_kml_poi/validate/$', views.add_kml_poi_validate, name='add_kml_poi_validate'),
    url(r'^add_poi/$', views.add_poi, name='add_poi'),
    url(r'^add_poi/validate/$', views.add_poi_validate, name='add_poi_validate'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Area(models.Model):
    area_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.pk)


class Plot(models.Model):
    area_id = models.ForeignKey(Area, on_delete=models.CASCADE)
    plot_id = models.IntegerField()
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    lat = models.CharField(max_length=100)
    lng = models.CharField(max_length=100)
    alt = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    polygon = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.pk)


class Public(models.Model):
    plot_code = models.ForeignKey(Plot, on_delete=models.CASCADE)
    floor_id = models.IntegerField()
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    lat = models.CharField(max_length=100)
    lng = models.CharField(max_length=100)
    alt = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    polygon = models.CharField(max_length=1000)

    def __str__(self):
        return self.name+" "+str(self.floor_id)


class Floor(models.Model):
    plot_id = models.ForeignKey(Plot, on_delete=models.CASCADE)
    floor_id = models.CharField(max_length=1000)
    description = models.CharField(default="NULL", max_length=1000)

    def __str__(self):
        return str(self.pk)


class POI(models.Model):
    floor_info = models.ForeignKey(Floor, default=1, on_delete=models.CASCADE)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    floor_id = models.CharField(max_length=1000)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100, blank=True)
    webaddress = models.CharField(default="NULL", max_length=100, blank=True)
    mobile = models.CharField(max_length=15, blank=True)
    lat = models.CharField(default="", max_length=100, blank=True)
    lng = models.CharField(default="", max_length=100, blank=True)
    alt = models.CharField(default="", max_length=100, blank=True)
    type = models.CharField(default="", max_length=100, blank=True)
    polygon = models.CharField(default="", max_length=1000, blank=True)
    assigned = models.BooleanField(default=False)

    def __str__(self):
        return self.name+" "+str(self.floor_id)


class File(models.Model):
    file = models.FileField(null=True, blank=True)

user/forms.py
from  django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import File, Plot, Public, POI, Floor


class RegistrationForm(ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput(render_value=False))
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password', 'password1']

        def clean(self):
                if self.cleaned_data['password'] != self.cleaned_data['password1']:
                        raise forms.ValidationError("The passwords did not match.  Please try again.")
                return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(label=(u'User Name'))
    password = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))


class UploadForm(ModelForm):
    class Meta:
        model = File
        fields = ['file']


class UpdateForm(ModelForm):
    class Meta:
        model = Plot
        fields = ['area_id', 'plot_id', 'name', 'description', 'lat', 'lng', 'alt', 'type', 'polygon']


class UpdatePublicForm(ModelForm):
    class Meta:
        model = Public
        fields = ['plot_code', 'floor_id', 'name', 'description', 'lat', 'lng', 'alt', 'type', 'polygon']


class UpdatePOIForm(ModelForm):
    class Meta:
        model = POI
        fields = ['floor_id', 'name', 'description', 'webaddress', 'mobile', 'lat', 'lng', 'alt', 'type', 'polygon']


class UpdateFloorForm(ModelForm):
    class Meta:
        model = Floor
        fields = ['plot_id', 'floor_id', 'description']

user/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from user.forms import RegistrationForm, LoginForm, UploadForm, UpdateForm, UpdatePOIForm, UpdatePublicForm, \
    UpdateFloorForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Plot, Public, Area, POI, Floor
from . import serializers
from django.contrib.auth import authenticate, login, logout
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from rest_framework.decorators import permission_classes
from fastkml import kml
from shapely.geometry import Point, Polygon
from django.views import generic
from pathlib import Path
import os
import csv


def index(request):
    return render(request, "base.html")


def upkml(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES or None)
        if form.is_valid():
            file = form.save(commit=False)
            file.save()
            uploaded_files = request.FILES['file']
            print(uploaded_files.name)
            temp = uploaded_files.name.split('_')
            path = 'Bangladesh/' + temp[0] + '/' + temp[1]
            os.makedirs(path, exist_ok=True)
            path += '/' + uploaded_files.name
            with open(path, 'wb+') as destination:
                for chunk in uploaded_files.chunks():
                    destination.write(chunk)
            parse(request, path)
       # return render(request, "base.html")
        return redirect('/user')
    else:
        form = UploadForm()
        return render(request, "upkml.html", {'form': form})


def update_plot(request, plot_id):
    plot = get_object_or_404(Plot, pk=plot_id)
    return render(request, "update.html", {'plot': plot})


def check_plot(request, plot_id):
    print("asche")
    if request.method == 'POST':
        form = UpdateForm(request.POST)
        if form.is_valid():
            print("asche")
            t = Plot.objects.get(id=plot_id)
            t.area_id = form.cleaned_data['area_id']
            t.plot_id = form.cleaned_data['plot_id']
            t.lat = form.cleaned_data['lat']
            t.lng = form.cleaned_data['lng']
            t.alt = form.cleaned_data['alt']
            t.name = form.cleaned_data['name']
            t.description = form.cleaned_data['description']
            t.type = form.cleaned_data['type']
            t.polygon = form.cleaned_data['polygon']
            t.save()
            area = str(form.cleaned_data['area_id'])
            plot = str(form.cleaned_data['plot_id'])
            path = 'Bangladesh' + '/' + '1' + '/' + area + '/' + '1_' + area + '_' + plot + '.kml'
            print(path)
            file = Path(path)
            if file.exists():
                os.remove(path)
            k = kml.KML()
            ns = '{http://www.opengis.net/kml/2.2}'
            d = kml.Document(ns, 'docid', 'docname', 'docdesc')
            k.append(d)
            desc = area + ' ' + plot + ' ' + form.cleaned_data['description'] + ' ' + form.cleaned_data['type']
            p = kml.Placemark(ns, 'id', form.cleaned_data['name'], desc)
            list = []
            print('full data')
            print(form.cleaned_data['polygon'])
            if 'NULL' in form.cleaned_data['polygon']:
                p.geometry = Point(float(form.cleaned_data['lat']), float(form.cleaned_data['lng']), float(form.cleaned_data['alt']))
            else:
                temp = form.cleaned_data['polygon']
                temp = temp.replace(', ', ',')
                temp1 = temp.split(',')
                for i in temp1:
                    strr = i
                    str1 = strr.split(' ')
                    print(str1)
                    list_temp = []
                    list_temp.append(float(str1[0]))
                    list_temp.append(float(str1[1]))
                    list_temp.append(float(str1[2]))
                    list.append(list_temp)
                    print(list)
                p.geometry = Polygon(list)
            d.append(p)
            out = open(path, 'w+')
            final = k.to_string(prettyprint=True)
            out.write(final)
            out.close()
            print(k.to_string(prettyprint=True))
        else:
            print(form.errors)
    return redirect('/user')


def registration(request):
        if request.user.is_authenticated():
            return HttpResponse("Already In")
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                User.objects.create_user(username=form.cleaned_data['first_name'],
                                         email=form.cleaned_data['email'],
                                         password=form.cleaned_data['password'],
                                         first_name=form.cleaned_data['first_name'],
                                         last_name=form.cleaned_data['last_name'],
                                         )
                return HttpResponseRedirect('/user/login')
            else:
                return render(request, "register.html", {'form': form})

        else:
            ''' user is not submitting the form, show them a blank registration form '''
            form = RegistrationForm()
            return render(request, "register.html", {'form': form})


def Login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/user/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request, "base.html")
            else:
                return render(request, "login.html", {'form': form})
        else:
            return render(request, "login.html", {'form': form})
    else:
        ''' user is not submitting the form, show the login form '''
        form = LoginForm()
        return render(request, "login.html", {'form': form})


def Logout(request):
    logout(request)
    return HttpResponseRedirect('/user/login')


@permission_classes([IsAuthenticated])
class UserList(viewsets.ModelViewSet):

    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer

    def perform_create(self, serializer):
        # serializer.validated_data.update({'company_id': get_company_id(self.request)})
        super().perform_create(serializer)

    def get_queryset(self):
        return super().get_queryset()


def parse(request,path):
    with open(path, 'r') as myfile:
        data = myfile.read()

   # print(data)
    k = kml.KML()
    k.from_string(data)
    features = list(k.features())
    print(len(features))
    f2 = list(features[0].features())
    print(len(f2))
    for i in f2:
        print(i.name+" "+i.description+" "+str(i.geometry))

        if "POINT" in str(i.geometry):
           # print("asche")
            temp = str(i.geometry).replace("POINT (", "").replace(")", "")
            temp = temp.replace("POINT Z (", "").replace(")", "")
            temp1 = temp.split()
            latitude = temp1[0]
            longitude = temp1[1]
            altitude = temp1[2]
            poly = "NULL"
            print(latitude+" "+longitude+" "+altitude)
        else:
            poly = str(i.geometry).replace("POLYGON((", "").replace("))", "")
            poly = poly.replace("POLYGON Z ((", "").replace("))", "")
            latitude = "NULL"
            longitude = "NULL"
            altitude = "NULL"
            print(poly)

        name = str(i.name)

        # area_id plot_id description type [optional-floor_id]
        total = str(i.description).split()
        if len(total) == 4:
            area = Area.objects.get(pk=int(total[0]))
            plot = int(total[1])
            descript = total[2]
            type = total[3]

            plot = Plot(area_id=area,
                        plot_id=plot,
                        name=name,
                        description=descript,
                        lat=latitude,
                        lng=longitude,
                        alt=altitude,
                        type=type,
                        polygon=poly)
            plot.save()
        else:
            print("floor e asche")
            plot_code = Plot.objects.get(plot_id=int(total[1]), area_id=Area.objects.get(pk=int(total[0])))
            description = total[2]
            type = total[3]
            floor_id = total[4]

            public = Public(plot_code=plot_code,
                            floor_id=floor_id,
                            name=name,
                            description=description,
                            lat=latitude,
                            lng=longitude,
                            alt=altitude,
                            type=type,
                            polygon=poly)
            public.save()
    return HttpResponse(data)


class PlotView(generic.ListView):
    template_name = 'plot.html'

    def get_queryset(self):
        return Plot.objects.all()


def public(request, plot_id):
    queryset = Public.objects.filter(plot_code=plot_id)
    plot = get_object_or_404(Plot, pk=plot_id)
    return render(request, 'public.html', {'Pub': queryset, 'name': plot.name})


def detail_public(request, id):
    pub = get_object_or_404(Public, pk=id)
    return render(request, 'detail_public.html', {'public': pub})


def detail(request, plot_id):
        plot = get_object_or_404(Plot, pk=plot_id)
        return render(request, 'detail.html', {'plot': plot})


def update_public(request, id):
    pub = get_object_or_404(Public, pk=id)
    return render(request, "update_public.html", {'public': pub})


def check_public(request, id):

user/templates/create_floor_form.html
{% extends "base.html" %}
{% block body %}

<div class="container">

  <form id="contact" action="" method="post">
      {% csrf_token %}
    <h3>Create Floor Form</h3>

    <fieldset>
        <strong><em>Plot Id:</em></strong>
      <input name = "plot_id" value="" type="text" tabindex="1" required>
    </fieldset>

    <fieldset>
        <strong><em>Floor_id:</em></strong>
        <input name = "floor_id" value="" type="text" tabindex="2" required autofocus>
    </fieldset>

     <fieldset>
        <strong><em>Description:</em></strong>
      <input name = "description" value="" type="text" tabindex="3">
    </fieldset>

    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>

  </form>
</div>

<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
  font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

body {
  font-family: "Roboto", Helvetica, Arial, sans-serif;
  font-weight: 100;
  font-size: 12px;
  line-height: 30px;
  color: #777;
  background: #f8f8f8;
}

.container {
  max-width: 500px;
  width: 100%;
  margin: 0 auto;
  position: relative;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea,
#contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

#contact {
  background: #F9F9F9;
  padding: 25px;
  margin: 0 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

#contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}

#contact h4 {
  margin: 5px 0 15px;
  display: block;
  font-size: 13px;
  font-weight: 400;
}

fieldset {
  border: medium none !important;
  margin: 0 0 5px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

#contact input[type="text"]:hover,
#contact input[type="email"]:hover,
#contact input[type="tel"]:hover,
#contact input[type="url"]:hover,
#contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

#contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

#contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

#contact button[type="submit"]:hover {
  background: #43A047;
  -webkit-transition: background 0.3s ease-in-out;
  -moz-transition: background 0.3s ease-in-out;
  transition: background-color 0.3s ease-in-out;
}

#contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.copyright {
  text-align: center;
}

#contact input:focus,
#contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

::-webkit-input-placeholder {
  color: #888;
}

:-moz-placeholder {
  color: #888;
}

::-moz-placeholder {
  color: #888;
}

:-ms-input-placeholder {
  color: #888;
}
</style>
{% endblock %}

user/templates/create_poi.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ plot }}{% endblock %}


{% block body %}

<script>
  $(document).ready(function(){
    $("#table tr").click(function(){
   $(this).addClass('selected').siblings().removeClass('selected');
});

$('.button').on('click', function(e){

    $.ajax({
        url: 'validate',
        data: {
          'poi': $("#table tr.selected td:first").html(),
          'lat': "{{ lat }}",
          'lng': "{{ lan }}",
          'alt': "{{ alt }}",
          'poly': "{{ poly }}",

        },
        dataType: 'json',
        success: function (data) {
          if (data.success) {

            $('#popup').css('z-index', '1000');
            $("#popup").show();
            $("#close").show();
            $('#hover').css('background-color', '#000000');
            $('#hover').css('opacity', '.6');
            $('#hover').css('z-index', '999');

            $("#hover").show();


          }
        }
      });

  $("#hover").click(function(){

		$(this).fadeOut();
    $("#popup").fadeOut();
	});

  // close on click to X
  $("#close").click(function(){

	$("#hover").fadeOut();
    $("#popup").fadeOut();

    // set the cookie
    $.cookie('showPopup', 'false', { expires: 7 });
	});



});


});
</script>




<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-6 col lg-6 col xs-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Upload KML</h3>
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            <p><input type="submit" value="Save" alt="register" /></p>
                        </form>
                        {% if error %}
                            <h3>{{ error }}</h3>
                        {% endif %}

                        {% if poi_list %}
                        <div class="scrollable">
                            <table class="table" id="table-kml">
                                <thead>
                                <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Type</th>
                                <th>Floor Id</th>
                                </tr>
                                </thead>
                                <tbody>

                                   {% for p in poi_list %}
                                <tr>
                                    <td>{{ p.pk }}</td>
                                    <td>{{ p.name }}</td>
                                    <td>{{ p.description }}</td>
                                    <td>{{ p.type }}</td>
                                    <td>{{ p.floor_id }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-6 col-md-6 col lg-6 col xs-6">


            <div class="panel panel-default">
                <div class="panel-body">
  <form id="contact" action="/user/create_poi_form/" method="post">
      {% csrf_token %}
    <h3>Create POI Form</h3>

    <fieldset>
        <strong><em>Floor_id:</em></strong>
        <input name = "floor_id" value="" type="text" tabindex="2" required autofocus>
    </fieldset>

     <fieldset>
        <strong><em>Name:</em></strong>
      <input name = "name" value="" type="text" tabindex="6" required>
    </fieldset>

     <fieldset>
        <strong><em>Description:</em></strong>
      <input name = "description" value="" type="text" tabindex="7">
    </fieldset>

    <fieldset>
        <strong><em>Web Address:</em></strong>
      <input name = "webaddress" value="" type="text" tabindex="3" >
    </fieldset>
    <fieldset>
        <strong><em>Contact no:</em></strong>
      <input name = "mobile" value="" type="text" tabindex="4" >
    </fieldset>

    <fieldset>
        <strong><em>Latitude:</em></strong>
      <input name = "lat" value="" type="text" tabindex="3" >
    </fieldset>
    <fieldset>
        <strong><em>Longitude:</em></strong>
      <input name = "lng" value="" type="text" tabindex="4" >
    </fieldset>
    <fieldset>
        <strong><em>Altitude:</em></strong>
      <input name = "alt" value="" type="text" tabindex="5" >
    </fieldset>

     <fieldset>
        <strong><em>Type:</em></strong>
      <input name = "type" value="" type="text" tabindex="8" >
    </fieldset>

     <fieldset>
        <strong><em>Polygon:</em></strong>
      <input name = "polygon" value="" type="text" tabindex="9" >
    </fieldset>


    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>

  </form>
                </div>

            </div>

        </div>

    </div>

</div>




  <div id="popup">
    <div id="close">X</div>
    <h2>Successfully added</h2>

  </div>


<style>
    .scrollable{

    height : 200px;
    overflow : scroll;
    }

      .thumb {
    height: 75px;
    border: 1px solid #000;
    margin: 10px 5px 0 0;
  }

.selected {
    background-color: #4CAF50;
    color: #FFF;
}

td {border: 1px #DDD solid; padding: 5px; cursor: pointer;}


.button {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 50px 0 5px;
  padding: 10px;
  font-size: 15px;
}




#popup{
  position:absolute;
  width:600px;
  height:180px;
  background:#fff;
  left:50%;
  top:50%;
  border-radius:5px;
  padding:60px 0;
  margin-left:-320px; /* width/2 + padding-left */
  margin-top:-150px; /* height/2 + padding-top */
  text-align:center;
  box-shadow:0 0 10px 0 #000;
  display : none;
  #tweet{
    color: #4099FF;
  }
}

#close{
  position:absolute;
  background:black;
  color:white;
  right:-15px;
  top:-15px;
  border-radius:50%;
  width:30px;
  height:30px;
  line-height:30px;
  text-align:center;
  font-size:8px;
  font-weight:bold;
  font-family:'Arial Black', Arial, sans-serif;
  cursor:pointer;
  box-shadow:0 0 10px 0 #000;
  display : none;

}

    #hover{
  position:absolute;

  width:100%;
  height:100%;
  opacity: .6
  display : none;



}


 @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
  font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

body {
  font-family: "Roboto", Helvetica, Arial, sans-serif;
  font-weight: 100;
  font-size: 12px;
  line-height: 30px;
  color: #777;
  background: #f8f8f8;
}

.container {
  max-width: 500px;
  width: 100%;
  margin: 0 auto;
  position: relative;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea,
#contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

#contact {
  background: #F9F9F9;
  padding: 10px;

  margin: 0 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

#contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}

#contact h4 {
  margin: 5px 0 15px;
  display: block;
  font-size: 13px;
  font-weight: 400;
}

fieldset {
  border: medium none !important;
  margin: 0 0 5px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

#contact input[type="text"]:hover,
#contact input[type="email"]:hover,
#contact input[type="tel"]:hover,
#contact input[type="url"]:hover,
#contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

#contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

#contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

#contact button[type="submit"]:hover {
  background: #43A047;
  -webkit-transition: background 0.3s ease-in-out;
  -moz-transition: background 0.3s ease-in-out;
  transition: background-color 0.3s ease-in-out;
}

#contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.copyright {
  text-align: center;
}

#contact input:focus,
#contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

::-webkit-input-placeholder {
  color: #888;
}

:-moz-placeholder {
  color: #888;
}

::-moz-placeholder {
  color: #888;
}

:-ms-input-placeholder {
  color: #888;

</style>

{% endblock %}